### ISSUE TITLE
pretrain dataset

### ISSUE THREAD

**Issue by hxu105** [DeepGraphLearning/GearNet#6]
Hi, I download about 38k pdb files by using the config files, and paper indicates the pretrain dataset is 805k. Should this be expected? Many thanks!

**Comment by Oxer11** [comment]
Hi! Since the AF DB is too large to directly load in the CPU memory, we instead do a Round-Robin pretraining on each species. https://github.com/DeepGraphLearning/GearNet/blob/09a4b92602aae261d10c18d9613b99ccc5a6ebc6/script/pretrain.py#L60-L68
If you don't specify a species, it will download each species one by one and pretrain our model on it. The species and split id can be passed when loading AF DB (https://torchdrug.ai/docs/api/datasets.html#alphafolddb).
